# Generated by Django 3.0 on 2019-12-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='or_id',
        ),
    ]
