# Generated by Django 3.0 on 2019-12-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191230_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='or_id',
            new_name='order_id',
        ),
    ]
